name: Deploy Lamda to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: deploy
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
      with:
        node-version: 17.x
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v2
      with:
        args: deploy
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}